### ISSUE TITLE
Bug #1

### ISSUE THREAD

**Issue by MihailHavenT** [Arechii/CallVote#6]
Hi Arechi, I wanted to report a new CallVote bug that occurs on my servers, so when I make a new callvote "successful" I wait maximum 5 minutes on the server and it shows again that "successful vote" on the server, it's like from new but delayed... 
You can check to correct the bugs and see other errors. Thanks for reading.

Best Regards, Mihail

**Comment by MihailHavenT** [comment]
TH'DR: and add "vote_help" in the translation configuration, just like the old callvote plugin... It's pretty useful this one :D

**Comment by ButteredToast26** [comment]
See this pull request for a fix    https://github.com/Arechii/CallVote/pull/7
